# Generated by Django 2.0.3 on 2018-03-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzacomment',
            name='comment',
            field=models.CharField(default='', max_length=3000),
            preserve_default=False,
        ),
    ]
