# Generated by Django 2.0.3 on 2018-03-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20180321_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='url_name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
