# Generated by Django 2.0.3 on 2018-03-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_pizzacomment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='pizzacomment',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
