# Generated by Django 2.0.3 on 2018-03-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20180321_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='url_name',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
    ]
