# Generated by Django 2.0.3 on 2018-03-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20180321_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='url_name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='pizzacomment',
            name='comment',
            field=models.TextField(max_length=3000),
        ),
    ]
